#!/bin/bash

echo""
echo""
echo please enter two integers seperated by a space
echo ''
PS3='Please choose from the menu'

read num1 num2
ansAvg=0
summation ()
{  min=$num1
   max=$num2
   counter=0
   sum1=0
   while [ $min -le $max ]; do
      let sum1="$sum1+$min"
      let counter="$counter+1"
      let min="$min+1"
   done
   echo   $sum1/$counter
}

avg ()
{
   result=0
   index=0;
   result=$(summation)
   sum=${result%/*}
   n=${result#*/}
   let avg="$sum/$n"
   echo $avg
}

OPTIONS="Even_Numbers Odd_Numbers Sum Average Quit"
   select opt in $OPTIONS; do
     if [ "$opt" = "Quit" ]; then
        
        echo done
        exit
     elif [ "$opt" = "Even_Numbers" ]; then
        counter=$num1
        while [ $counter -le $num2 ]; do
          [ $((counter%2)) -eq 0 ] && echo $counter
          let counter=$counter+1
        done
     elif [ "$opt" = "Odd_Numbers" ]; then
        counter=$num1
        while [ $counter -le $num2 ]; do
           [ $((counter%2)) -ne 0 ] && echo $counter
           let counter=$counter+1
        done
     elif [ "$opt" = "Sum" ]; then
        result=$(summation)
        sum=${result%/*}
        echo The summation of the integer sequence is: $sum 
     elif [ "$opt" = "Average" ]; then
        echo The average of these numbers is:
        avg
     else
        clear
        echo bad option
     fi
   done

   
