#!/bin/bash

echo""
echo""
echo please enter two integers seperated by a space


read num1 num2

summation ()
{  min=$num1
   max=$num2
   counter=0
   sum1=0
   while [ $min -le $max ]; do
      let sum1="$sum1+$min"
      let counter="$counter+1"
      let min="$min+1"
   done
   echo   $sum1/$counter
}

avg ()
{
   result=0
   index=0;
   let index="$num2-$num1"
   result=$(summation)
   sum=${result%/*}
   n=${result#*/}
   let avg="$sum/$n"
   echo $avg
}

OPTIONS="Even_Numbers Odd_Numbers Sum Average Quit"
   select opt in $OPTIONS; do
     if [ "$opt" = "Quit" ]; then
        
       echo done
        exit
     elif [ "$opt" = "Even_Numbers" ]; then
        COUNTER=$num1
        while [ $COUNTER -lt $num2 ]; do
          [ $((COUNTER%2)) -eq 0 ] && echo $COUNTER
          let COUNTER=$COUNTER+1
          done
     elif [ "$opt" = "Odd_Numbers" ]; then
        COUNTER=$num1
        while [ $COUNTER -lt $num2 ]; do
          [ $((COUNTER%2)) -ne 0 ] && echo $COUNTER
          let COUNTER=$COUNTER+1
          done
     elif [ "$opt" = "Sum" ]; then
        result=$(summation)
        sum=${result%/*}
        echo The summation of the integer sequence is: $sum 
     elif [ "$opt" = "Average" ]; then
        let avg1=avg
        echo The average of these numbers is: $avg1 
     else
        clear
        echo bad option
     fi
   done

   
